# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-DOM
version:      1.44
version_from: lib/XML/DOM.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    XML::Parser:                   2.30
    XML::Parser::PerlSAX:          0.07
    XML::RegExp:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
